# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/673b4118-e6ec-463c-976b-4134a21381d5";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-313429a1-3f97-4a54-9b1d-77d3d59fb94c".device = "/dev/disk/by-uuid/313429a1-3f97-4a54-9b1d-77d3d59fb94c";

   boot.initrd.luks.devices."luks-c9921ad3-50d4-47e6-9f77-d5721d75d1e1".device = "/dev/disk/by-uuid/c9921ad3-50d4-47e6-9f77-d5721d75d1e1";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/786D-7B92";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c77b0571-e6e0-4557-869b-073dc267fc86"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp42s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
