{config, ...}:
{
 imports = [
 ./dualsensectl.nix
 ./firefox.nix
 ./librewolf.nix
 ./mpv.nix
 ./mullvad-browser.nix
 ./nicotine-plus.nix
 ./protonmail-desktop.nix
 ./proton-pass.nix
 ./qpwgraph.nix
 ./schismtracker.nix
 ./spotify.nix
 ./sunshine.nix
 ./telegram-desktop.nix
 ./uxplay.nix
 ./vesktop.nix
 ./feishin.nix
 ./audacity.nix
 ./tor-browser.nix
 ./prismlauncher.nix
 ./strawberry.nix
 ./tigervnc.nix
 ./veracrypt.nix
 ./discord.nix
 ./easyeffects.nix
 ./konsole.nix
 ./opensnitch.nix
];
}
